.de Sh
.br
.ne 5
.PP
\fB\\$1\fR
.PP
..
.de Sp
.if t .sp .5v
.if n .sp
..
.ie n \{\
.tr \(bs-\*(Tr
.ds -- \(bs-
.if (\n(.H=4u)&(1m=24u) .ds -- \(bs\h'-12u'\(bs\h'-12u'-\" diablo 10 pitch
.if (\n(.H=4u)&(1m=20u) .ds -- \(bs\h'-12u'\(bs\h'-8u'-\" diablo 12 pitch
.ds L" ""
.ds R" ""
.ds L' '
.ds R' '
'br\}
.el\{\
.ds -- \(em\|
.tr \*(Tr
.ds L" ``
.ds R" ''
.ds L' `
.ds R' '
'br\}
.TH XSIS 1CAD "10 Oct 1991" "" Preliminary
.SH NAME
xsis \- graphical interface to sis based on Athena widget set.
.SH SYNOPSYS
.B xsis
[\fB-sis \fIpathname\fP]
[\fB-debug\fP]
[\fIX Toolkit options...\fP]
.SH DESCRIPTION
\fBxsis\fP is a graphical front-end for
\fBsis\fP, the Berkeley Sequential Interactive
System.
The initial goal of this program is to provide support for the
\fBplot\fP command from earlier versions of \fBsis\fP
in a manner which is portable under the MIT distribution of X11R4.
\fBxsis\fP is based on the Athena widget set and the X Toolkit,
and works with \fBsis\fP versions 1.1 and later.
.PP
\fBxsis\fP runs a copy of \fBsis\fP as a child process.
This means that any ordinary command-line version of \fBsis\fP can
be run under \fBxsis\fP without recompiling anything.
To locate a copy of \fBsis\fP to run,
\fBxsis\fP first searches the directories
specified in the \fB$PATH\fP environment variable.
If there is no executable named ``sis'' there,
it tries the directory that
\fBxsis\fP is located in.
.PP
The widget hierarchy used by \fBxsis\fP
is documented below so you can customize it using X resources.
Notice that the names of some top level windows
depend on what data has been displayed in them (e.g. the network plot windows).
The instance name is shown first followed by the class name in parenthesis.
Although X11 refers to a top level window as a shell, we will loosely
refer to them as windows to avoid confusion with command-line shells
such as csh.
\fBxsis\fP uses multiple top level windows which are described below.

The \fBsis\fP graphics package file graphics.doc describes
the interface conventions between \fBxsis\fP and \fBsis\fP,
and outlines how to add new graphics features.

.SH OPTIONS
\fBxsis\fP accepts the following options:

.TP 4
\fB-sis \fIpathname\fP
Run specified version of \fBsis\fP instead of searching in the \fBxsis\fP
and \fB$PATH\fP directories.
.TP 4
\fB-debug\fP
Produce \fBxsis\fP debug output which is both verbose and invaluable when
there are problems.
.TP 4
\fB-bg \fIcolor\fP
Set the background color for all windows.
.TP 4
\fB-bd \fIcolor\fP
Set the border color for all windows.
.TP 4
\fB-bw \fIn\fP
Set the border width to \fIn\fP pixels for all windows.
.TP 4
\fB-display \fIdisplayname\fP
Use the specified display for all windows.
.TP 4
\fB-fg \fIcolor\fP
Set the foreground color for all windows.
.TP 4
\fB-fn \fIfontname\fP
Use specified font in all windows.
Since \fBxsis\fP has multiple windows, it is usually more convenient to
set the font for each window separately using \fB.Xdefaults\fP
as described below.
.TP 4
\fB-geometry \fIvalue\fP
Set the initial geometry of the command window.
.TP 4
\fB-name \fIvalue\fP
Use an alternate name for looking up resources in the \fB.Xdefaults\fP file.
.PP
\fBxsis\fP also supports all other standard X Toolkit options, such as
\fB-font\fP and \fB-foreground\fP.

.SH SIS COMMANDS
When \fBsis\fP is run using the \fBxsis\fP interface,
you can use the following graphics commands.

.TP 4
\fBplot_blif [-n \fI<name>\fB] [-g \fI<geom>\fB] [-k] [-i] [-r]\fP
Create a new plot window and display the current network.
.br
.B -n <name>
Specifies the plot window name instead of using the network name.
.br
.B -g <geom>
Give the initial geometry of the window, using the standard X11
format: WxH+X+Y.
.br
.B -r
Replace the drawing in the last window
created with the same plot name.
.br
.B -k
Kill the last plot with the same plot name.
.br
.B -i
Label the plot with the internal network names used by \fBsis\fP.

.TP 4
\fB_speed_plot [-n \fIname\fB] [-c] [-g] [-h] [-t \fIn.n\fB] [-w \fIn.n\fB] [-d \fIn\fB]\fP
Without -h or -c, this adds buttons to the plot window to select either
the critical path or cutset.
.br
.B -n
.I name
Specifies the plot window name instead of using the network name.
.br
.B -c
Highlight the minimum weight cutset.
.br
.B -h
Highlight nodes on a critical path.
.br
.B -g
Label the nodes with their gate names (after technology mapping).
.br
.B -t
.I n.n
Critical threshold.
.br
.B -w
.I n.n
Relative weight of area.
.br
.B -d
.I n
Distance for collapsing.

.TP 4
\fBhelp\fP [-g \fI<geom>\fP] \fItopic\fP
Display help for the topic in a separate help window.
Only one help window is ever open, so
repeated help commands just change the topic.

.SH COMMAND WINDOW
This is the main window where you enter \fBsis\fP commands and view
\fBsis\fP text output.
.sp 1
.nf
        xsis (XSis)
                paned (Paned)
                        box (Box)
                                quit (Command)
                                clear (Command)
                                print (Command)
                                version (Label)
                        cmdline (Text)
                        textout (Text)
.fi
.PP
The command text widget supports several standard control characters:
^D for EOF, ^U for kill, ^C for interrupt, and ^D/ESC for file completion.

.SH NETWORK PLOT WINDOW
This window is created for each separate network plot you make.
By default it shows the network structure as described by the write_blif
command.
You can display the internal \fBsis\fP network structure by using
\fBplot_blif -i\fP.
For default actions, clicking the left button on a node highlights the
node and its fanins and fanouts.
Clicking the middle button issues a \fBprint\fP command on the node
in the command window.
.sp 1
.nf
        xsis (XSis)
                \fInetwork-name\fP (TopLevelShell)
                        blifPane (Paned)
                                box (Box)
                                        close (Command)
				label (Label)
                                netPlot (NetPlot)
.fi
.PP
The NetPlot widget supports the following resources:
.sp 1
.TS
box;
l | l | l | l.
Name	Type	Default	Description
_
background	Pixel	white	Background color of plot.
foreground1	Pixel	black	Color of internal nodes.
foreground2	Pixel	black	Color of PI nodes.
foreground3	Pixel	black	Color of PO nodes.
foreground4	Pixel	black	Color of graph edges.
hilight	Pixel	black	Highlighting color for plot.
font	FontStruct	?	Font for all text in the plot.
_
.TE
.sp 1
.PP
There are two defined actions:

.TP 8
.B SelectMe ()
Highlight a node, its fanins and fanouts.

.TP 8
.B NodeCmd ([\fIhit\fB],[\fImiss\fB])\fP
Execute a \fBsis\fP command on a node.
The first \fB%s\fP in the \fIhit\fP parameter is replaced by the
node which was hit before the command is sent to \fBsis\fP.
The \fImiss\fP command is executed if no node was hit by the event.

.SH HELP WINDOW
The help window is a separate window for displaying \fBsis\fP on-line help.
Only one help window is ever created and each new topic you select
is displayed in this window.
.sp 1
.nf
        xsis help (TopLevelShell)
                paned1 (Paned)
                        box (Box)
                                close (Command)
                                label (Label)
                        paned2 (Paned)
                                topicList (Viewport)
                                        list (List)
                                helpText (Text)
.fi
.SH "X DEFAULTS"
Using the above window hierarchies, you can customize \fBxsis\fP
with resources specified in the \fB.Xdefaults\fP file.
To change all pushbuttons to red:
.sp 1
.nf
        XSis*Command*foreground: red
.fi
.sp 1
To change only the close pushbuttons to red:
.sp 1
.nf
        XSis*close*foreground: red
.fi
.sp 1
To change the color of PO nodes in all plots to orange:
.sp 1
.nf
        XSis*netPlot.foreground3: orange
.fi
.sp 1
The resources which most closely match the network plot to the
old \fBplot\fP command in \fBsis\fP:
.sp 1
.TS
l l.
        XSis*netPlot.background:	white
        XSis*netPlot.foreground1:	blue
        XSis*netPlot.foreground2:	red
        XSis*netPlot.foreground3:	green
        XSis*netPlot.foreground4:	black
        XSis*netPlot.font:	courier10
.TE
.sp 1
For a list of other resources which can be changed, see the resource
list at the beginning of file \fBxsis.c\fP,
and the MIT Athena Widgets documentation.

.SH FILES
.TS
l l.
/projects/sis/sis/common/src/xsis/	- source for xsis
~/.Xdefaults	- resources to customize \fBxsis\fP
.TE

.SH "SEE ALSO"
sis(1CAD)

.SH DIAGNOSTICS
If you use \fBxsis\fP with a version of \fBsis\fP which does not support
graphics, you will get a message similar to:
.sp 1
.nf
	$ xsis -sis sis1.0
	sis1.0: unknown option X
	usage: sis1.0 [-sx] [-c cmd] [-f script] ...
.fi
.sp 1
.PP
If no directory in your path contains an executable named
\fBsis\fP:
.sp 1
.nf
	$ xsis
	xsis: could not find "sis" in your path.
.fi
.sp 1

.SH BUGS
Typing \fB^Z\fP in the command window does not interrupt or
suspend the program,
and suspending \fBxsis\fP from the shell only suspends it
and not the associated \fBsis\fP child process.
.PP
The Athena text widget used for the command window display does not support
cursor positioning, so using the \fBsis\fP shell escape (!) with
commands such as \fImore\fP or \fIvi\fP does not work very well.
.PP
Since graphics commands such as plot_blif must be supported by the
underlying version of \fBsis\fP,
they really should be documented there somehow.

.SH AUTHORS
Paul Stephan
.br
Copyright 1991 by the Regents of the Univerity of California.
