
#line 3 "lex.GENLIB_yy.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define GENLIB_yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define GENLIB_yynoreturn __attribute__((__noreturn__))
#else
#define GENLIB_yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (GENLIB_yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((GENLIB_yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE GENLIB_yyrestart( GENLIB_yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(GENLIB_yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct GENLIB_yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t GENLIB_yy_size_t;
#endif

extern int GENLIB_yyleng;

extern FILE *GENLIB_yyin, *GENLIB_yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    #define YY_LESS_LINENO(n)
    #define YY_LINENO_REWIND_TO(ptr)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define GENLIB_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up GENLIB_yytext. */ \
        int GENLIB_yyless_macro_arg = (n); \
        YY_LESS_LINENO(GENLIB_yyless_macro_arg);\
		*GENLIB_yy_cp = (GENLIB_yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(GENLIB_yy_c_buf_p) = GENLIB_yy_cp = GENLIB_yy_bp + GENLIB_yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up GENLIB_yytext again */ \
		} \
	while ( 0 )
#define unput(c) GENLIB_yyunput( c, (GENLIB_yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct GENLIB_yy_buffer_state
	{
	FILE *GENLIB_yy_input_file;

	char *GENLIB_yy_ch_buf;		/* input buffer */
	char *GENLIB_yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int GENLIB_yy_buf_size;

	/* Number of characters read into GENLIB_yy_ch_buf, not including EOB
	 * characters.
	 */
	int GENLIB_yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int GENLIB_yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int GENLIB_yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int GENLIB_yy_at_bol;

    int GENLIB_yy_bs_lineno; /**< The line count. */
    int GENLIB_yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int GENLIB_yy_fill_buffer;

	int GENLIB_yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via GENLIB_yyrestart()), so that the user can continue scanning by
	 * just pointing GENLIB_yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t GENLIB_yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t GENLIB_yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * GENLIB_yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (GENLIB_yy_buffer_stack) \
                          ? (GENLIB_yy_buffer_stack)[(GENLIB_yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (GENLIB_yy_buffer_stack)[(GENLIB_yy_buffer_stack_top)]

/* GENLIB_yy_hold_char holds the character lost when GENLIB_yytext is formed. */
static char GENLIB_yy_hold_char;
static int GENLIB_yy_n_chars;		/* number of characters read into GENLIB_yy_ch_buf */
int GENLIB_yyleng;

/* Points to current character in buffer. */
static char *GENLIB_yy_c_buf_p = NULL;
static int GENLIB_yy_init = 0;		/* whether we need to initialize */
static int GENLIB_yy_start = 0;	/* start state number */

/* Flag which is used to allow GENLIB_yywrap()'s to do buffer switches
 * instead of setting up a fresh GENLIB_yyin.  A bit of a hack ...
 */
static int GENLIB_yy_did_buffer_switch_on_eof;

void GENLIB_yyrestart ( FILE *input_file  );
void GENLIB_yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE GENLIB_yy_create_buffer ( FILE *file, int size  );
void GENLIB_yy_delete_buffer ( YY_BUFFER_STATE b  );
void GENLIB_yy_flush_buffer ( YY_BUFFER_STATE b  );
void GENLIB_yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void GENLIB_yypop_buffer_state ( void );

static void GENLIB_yyensure_buffer_stack ( void );
static void GENLIB_yy_load_buffer_state ( void );
static void GENLIB_yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER GENLIB_yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE GENLIB_yy_scan_buffer ( char *base, GENLIB_yy_size_t size  );
YY_BUFFER_STATE GENLIB_yy_scan_string ( const char *GENLIB_yy_str  );
YY_BUFFER_STATE GENLIB_yy_scan_bytes ( const char *bytes, int len  );

void *GENLIB_yyalloc ( GENLIB_yy_size_t  );
void *GENLIB_yyrealloc ( void *, GENLIB_yy_size_t  );
void GENLIB_yyfree ( void *  );

#define GENLIB_yy_new_buffer GENLIB_yy_create_buffer
#define GENLIB_yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        GENLIB_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            GENLIB_yy_create_buffer( GENLIB_yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_is_interactive = is_interactive; \
	}
#define GENLIB_yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        GENLIB_yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            GENLIB_yy_create_buffer( GENLIB_yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_at_bol)

/* Begin user sect3 */
typedef flex_uint8_t YY_CHAR;

FILE *GENLIB_yyin = NULL, *GENLIB_yyout = NULL;

typedef int GENLIB_yy_state_type;

extern int GENLIB_yylineno;
int GENLIB_yylineno = 1;

extern char *GENLIB_yytext;
#ifdef GENLIB_yytext_ptr
#undef GENLIB_yytext_ptr
#endif
#define GENLIB_yytext_ptr GENLIB_yytext

static GENLIB_yy_state_type GENLIB_yy_get_previous_state ( void );
static GENLIB_yy_state_type GENLIB_yy_try_NUL_trans ( GENLIB_yy_state_type current_state  );
static int GENLIB_yy_get_next_buffer ( void );
static void GENLIB_yynoreturn GENLIB_yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up GENLIB_yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(GENLIB_yytext_ptr) = GENLIB_yy_bp; \
	GENLIB_yyleng = (int) (GENLIB_yy_cp - GENLIB_yy_bp); \
	(GENLIB_yy_hold_char) = *GENLIB_yy_cp; \
	*GENLIB_yy_cp = '\0'; \
	(GENLIB_yy_c_buf_p) = GENLIB_yy_cp;
#define YY_NUM_RULES 23
#define YY_END_OF_BUFFER 24
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct GENLIB_yy_trans_info
	{
	flex_int32_t GENLIB_yy_verify;
	flex_int32_t GENLIB_yy_nxt;
	};
static const flex_int16_t GENLIB_yy_accept[73] =
    {   0,
        0,    0,   24,   22,   20,   20,    6,   22,   21,    7,
        2,    3,    9,    8,   19,   22,   19,    4,    5,   19,
       19,   19,   19,   19,   19,   20,    0,   21,    0,    0,
       19,   19,    0,   18,    0,   19,   19,   19,   19,   19,
       19,   19,    1,    0,    0,    0,    0,   19,   19,   19,
       19,   19,   11,   15,    0,   19,   19,   10,   19,   19,
       19,   12,   16,   17,   19,   19,   19,   13,   19,   19,
       14,    0
    } ;

static const YY_CHAR GENLIB_yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    2,    4,    5,    6,    1,    1,    1,    7,    8,
        9,   10,   11,    1,   12,   13,    1,   14,   15,   16,
       16,   16,   16,   16,   16,   16,   16,    1,   17,    1,
       18,    1,    1,    1,   19,   20,   21,   20,   22,   20,
       23,   24,   25,   20,   20,   26,   20,   27,   28,   29,
       30,   31,   32,   33,   20,   20,   20,   20,   20,   20,
        1,    1,    1,    1,   20,    1,   20,   20,   20,   20,

       34,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,   20,   20,   20,   20,   20,   20,   20,   20,
       20,   20,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR GENLIB_yy_meta[35] =
    {   0,
        1,    1,    2,    1,    3,    1,    1,    1,    1,    1,
        1,    4,    4,    4,    4,    4,    1,    1,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4
    } ;

static const flex_int16_t GENLIB_yy_base[76] =
    {   0,
        0,    0,  173,  174,   33,   35,  174,    0,    0,  174,
      174,  174,  174,   26,   30,   33,   48,  174,  174,  159,
       39,   40,   41,   43,   44,   69,  164,    0,   59,   81,
      153,    0,  114,  174,   62,    0,  138,   42,   52,   66,
       73,   68,  174,    0,   76,    0,   90,   90,  107,   80,
       67,  101,  149,  148,  118,   94,   95,  147,  111,  124,
      112,  146,  145,  144,  128,  118,   98,  133,  129,  130,
      132,  174,  163,  167,   54
    } ;

static const flex_int16_t GENLIB_yy_def[76] =
    {   0,
       72,    1,   72,   72,   72,   72,   72,   73,   74,   72,
       72,   72,   72,   72,   75,   72,   75,   72,   72,   75,
       75,   75,   75,   75,   75,   72,   73,   74,   72,   72,
       75,   17,   72,   72,   33,   17,   75,   75,   75,   75,
       75,   75,   72,   30,   72,   35,   72,   37,   37,   75,
       75,   75,   75,   75,   72,   75,   75,   75,   75,   75,
       75,   75,   75,   75,   75,   75,   75,   75,   75,   75,
       75,    0,   72,   72,   72
    } ;

static const flex_int16_t GENLIB_yy_nxt[209] =
    {   0,
        4,    5,    6,    7,    8,    9,   10,   11,   12,   13,
       14,   15,   16,   17,   17,   17,   18,   19,   20,   20,
       21,   20,   22,   20,   20,   23,   20,   20,   24,   20,
       20,   25,   20,   20,   26,   26,   26,   26,   29,   30,
       30,   30,   29,   32,   32,   32,   33,   33,   33,   34,
       34,   72,   72,   72,   72,   72,   72,   31,   39,   40,
       35,   36,   36,   36,   72,   42,   38,   41,   50,   37,
       26,   26,   33,   33,   33,   46,   46,   46,   72,   72,
       72,   37,   34,   34,   51,   72,   47,   47,   58,   55,
       55,   55,   72,   35,   44,   44,   44,   54,   52,   53,

       72,   31,   45,   55,   55,   55,   72,   72,   34,   34,
       72,   56,   57,   72,   45,   34,   34,   72,   31,   34,
       34,   59,   69,   72,   72,   61,   60,   33,   33,   33,
       72,   55,   55,   55,   62,   45,   72,   63,   64,   66,
       72,   72,   72,   68,   72,   72,   67,   45,   47,   48,
       72,   49,   49,   49,   65,   70,   72,   72,   72,   72,
       72,   72,   71,   27,   27,   72,   27,   28,   43,   28,
       28,   72,   72,    3,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,

       72,   72,   72,   72,   72,   72,   72,   72
    } ;

static const flex_int16_t GENLIB_yy_chk[209] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    5,    5,    6,    6,   14,   14,
       14,   14,   15,   15,   15,   15,   16,   16,   16,   17,
       17,   21,   22,   23,   38,   24,   25,   75,   22,   23,
       17,   17,   17,   17,   39,   25,   21,   24,   38,   17,
       26,   26,   29,   29,   29,   35,   35,   35,   40,   51,
       42,   17,   30,   30,   39,   41,   45,   45,   51,   45,
       45,   45,   50,   30,   30,   30,   30,   42,   40,   41,

       48,   48,   30,   47,   47,   47,   56,   57,   49,   49,
       67,   50,   50,   52,   30,   33,   33,   49,   49,   55,
       55,   52,   67,   59,   61,   57,   56,   33,   33,   33,
       66,   55,   55,   55,   59,   33,   60,   60,   60,   61,
       65,   69,   70,   66,   71,   68,   65,   33,   37,   37,
       37,   37,   37,   37,   60,   69,   64,   63,   62,   58,
       54,   53,   70,   73,   73,   31,   73,   74,   27,   74,
       74,   20,    3,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,
       72,   72,   72,   72,   72,   72,   72,   72,   72,   72,

       72,   72,   72,   72,   72,   72,   72,   72
    } ;

static GENLIB_yy_state_type GENLIB_yy_last_accepting_state;
static char *GENLIB_yy_last_accepting_cpos;

extern int GENLIB_yy_flex_debug;
int GENLIB_yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define GENLIB_yymore() GENLIB_yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *GENLIB_yytext;
#line 1 "readliblex.l"
#line 2 "readliblex.l"
/* file @(#)readliblex.l	1.1                      */
/* last modified on 5/29/91 at 12:35:32   */
#include "genlib_int.h"
#include "readlib.h"
#undef input
#undef unput
#ifdef FLEX_SCANNER
#undef YY_INPUT
#define YY_INPUT(buf,result,max) (result = genlib_input(buf, max))
#endif

static char *file_string;
static int file_mode;
static int nbuffer;
static char buffer[20];

/*alnum			[-A-Za-z0-9_.<>$%^&|{}[\]:,?/@]*/
#line 527 "lex.GENLIB_yy.c"
#line 528 "lex.GENLIB_yy.c"

#define INITIAL 0

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int GENLIB_yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int GENLIB_yylex_destroy ( void );

int GENLIB_yyget_debug ( void );

void GENLIB_yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE GENLIB_yyget_extra ( void );

void GENLIB_yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *GENLIB_yyget_in ( void );

void GENLIB_yyset_in  ( FILE * _in_str  );

FILE *GENLIB_yyget_out ( void );

void GENLIB_yyset_out  ( FILE * _out_str  );

			int GENLIB_yyget_leng ( void );

char *GENLIB_yyget_text ( void );

int GENLIB_yyget_lineno ( void );

void GENLIB_yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int GENLIB_yywrap ( void );
#else
extern int GENLIB_yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void GENLIB_yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef GENLIB_yytext_ptr
static void GENLIB_yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int GENLIB_yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int GENLIB_yyinput ( void );
#else
static int input ( void );
#endif

#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( GENLIB_yytext, (size_t) GENLIB_yyleng, 1, GENLIB_yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( GENLIB_yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( GENLIB_yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (GENLIB_yy_size_t) max_size, GENLIB_yyin)) == 0 && ferror(GENLIB_yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(GENLIB_yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "GENLIB_yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef GENLIB_yyterminate
#define GENLIB_yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) GENLIB_yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int GENLIB_yylex (void);

#define YY_DECL int GENLIB_yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after GENLIB_yytext and GENLIB_yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	GENLIB_yy_state_type GENLIB_yy_current_state;
	char *GENLIB_yy_cp, *GENLIB_yy_bp;
	int GENLIB_yy_act;
    
	if ( !(GENLIB_yy_init) )
		{
		(GENLIB_yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (GENLIB_yy_start) )
			(GENLIB_yy_start) = 1;	/* first start state */

		if ( ! GENLIB_yyin )
			GENLIB_yyin = stdin;

		if ( ! GENLIB_yyout )
			GENLIB_yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			GENLIB_yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				GENLIB_yy_create_buffer( GENLIB_yyin, YY_BUF_SIZE );
		}

		GENLIB_yy_load_buffer_state(  );
		}

	{
#line 28 "readliblex.l"


#line 748 "lex.GENLIB_yy.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		GENLIB_yy_cp = (GENLIB_yy_c_buf_p);

		/* Support of GENLIB_yytext. */
		*GENLIB_yy_cp = (GENLIB_yy_hold_char);

		/* GENLIB_yy_bp points to the position in GENLIB_yy_ch_buf of the start of
		 * the current run.
		 */
		GENLIB_yy_bp = GENLIB_yy_cp;

		GENLIB_yy_current_state = (GENLIB_yy_start);
GENLIB_yy_match:
		do
			{
			YY_CHAR GENLIB_yy_c = GENLIB_yy_ec[YY_SC_TO_UI(*GENLIB_yy_cp)] ;
			if ( GENLIB_yy_accept[GENLIB_yy_current_state] )
				{
				(GENLIB_yy_last_accepting_state) = GENLIB_yy_current_state;
				(GENLIB_yy_last_accepting_cpos) = GENLIB_yy_cp;
				}
			while ( GENLIB_yy_chk[GENLIB_yy_base[GENLIB_yy_current_state] + GENLIB_yy_c] != GENLIB_yy_current_state )
				{
				GENLIB_yy_current_state = (int) GENLIB_yy_def[GENLIB_yy_current_state];
				if ( GENLIB_yy_current_state >= 73 )
					GENLIB_yy_c = GENLIB_yy_meta[GENLIB_yy_c];
				}
			GENLIB_yy_current_state = GENLIB_yy_nxt[GENLIB_yy_base[GENLIB_yy_current_state] + GENLIB_yy_c];
			++GENLIB_yy_cp;
			}
		while ( GENLIB_yy_base[GENLIB_yy_current_state] != 174 );

GENLIB_yy_find_action:
		GENLIB_yy_act = GENLIB_yy_accept[GENLIB_yy_current_state];
		if ( GENLIB_yy_act == 0 )
			{ /* have to back up */
			GENLIB_yy_cp = (GENLIB_yy_last_accepting_cpos);
			GENLIB_yy_current_state = (GENLIB_yy_last_accepting_state);
			GENLIB_yy_act = GENLIB_yy_accept[GENLIB_yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

do_action:	/* This label is used only to access EOF actions. */

		switch ( GENLIB_yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*GENLIB_yy_cp = (GENLIB_yy_hold_char);
			GENLIB_yy_cp = (GENLIB_yy_last_accepting_cpos);
			GENLIB_yy_current_state = (GENLIB_yy_last_accepting_state);
			goto GENLIB_yy_find_action;

case 1:
/* rule 1 can match eol */
YY_RULE_SETUP
#line 30 "readliblex.l"
{ 
   			    int i;
			    GENLIB_yytext[GENLIB_yyleng-1] = '\0';
			    for(i = 0; i < GENLIB_yyleng; i++) GENLIB_yytext[i] = GENLIB_yytext[i+1];
			    GENLIB_yyleng -= 2;
			    return IDENTIFIER; 
			}
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 38 "readliblex.l"
{ return LPAREN; }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 39 "readliblex.l"
{ return RPAREN; }
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 40 "readliblex.l"
{ return SEMI; }
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 41 "readliblex.l"
{ return ASSIGN; }
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 42 "readliblex.l"
{ return OPR_NOT; }
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 43 "readliblex.l"
{ return OPR_NOT_POST; }
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 44 "readliblex.l"
{ return OPR_OR; }
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 45 "readliblex.l"
{ return OPR_AND; }
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 47 "readliblex.l"
{ return GATE; }
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 48 "readliblex.l"
{ return PIN; }
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 49 "readliblex.l"
{ return LATCH; }
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 50 "readliblex.l"
{ return CONTROL; }
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 51 "readliblex.l"
{ return CONSTRAINT; }
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 52 "readliblex.l"
{ return SEQ; }
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 53 "readliblex.l"
{ return CONST0; }
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 54 "readliblex.l"
{ return CONST1; }
	YY_BREAK
case 18:
/* rule 18 can match eol */
YY_RULE_SETUP
#line 55 "readliblex.l"
{ return REAL;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 56 "readliblex.l"
{ return IDENTIFIER; }
	YY_BREAK
case 20:
/* rule 20 can match eol */
YY_RULE_SETUP
#line 57 "readliblex.l"
;
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 58 "readliblex.l"
; 		/* comments */
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 60 "readliblex.l"
{ GENLIB_yyerror("bad character"); }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 62 "readliblex.l"
ECHO;
	YY_BREAK
#line 929 "lex.GENLIB_yy.c"
case YY_STATE_EOF(INITIAL):
	GENLIB_yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int GENLIB_yy_amount_of_matched_text = (int) (GENLIB_yy_cp - (GENLIB_yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*GENLIB_yy_cp = (GENLIB_yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed GENLIB_yyin at a new source and called
			 * GENLIB_yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(GENLIB_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_input_file = GENLIB_yyin;
			YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for GENLIB_yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since GENLIB_yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (GENLIB_yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf[(GENLIB_yy_n_chars)] )
			{ /* This was really a NUL. */
			GENLIB_yy_state_type GENLIB_yy_next_state;

			(GENLIB_yy_c_buf_p) = (GENLIB_yytext_ptr) + GENLIB_yy_amount_of_matched_text;

			GENLIB_yy_current_state = GENLIB_yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * GENLIB_yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			GENLIB_yy_next_state = GENLIB_yy_try_NUL_trans( GENLIB_yy_current_state );

			GENLIB_yy_bp = (GENLIB_yytext_ptr) + YY_MORE_ADJ;

			if ( GENLIB_yy_next_state )
				{
				/* Consume the NUL. */
				GENLIB_yy_cp = ++(GENLIB_yy_c_buf_p);
				GENLIB_yy_current_state = GENLIB_yy_next_state;
				goto GENLIB_yy_match;
				}

			else
				{
				GENLIB_yy_cp = (GENLIB_yy_c_buf_p);
				goto GENLIB_yy_find_action;
				}
			}

		else switch ( GENLIB_yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(GENLIB_yy_did_buffer_switch_on_eof) = 0;

				if ( GENLIB_yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * GENLIB_yy_get_next_buffer() to have set up
					 * GENLIB_yytext, we can now set up
					 * GENLIB_yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(GENLIB_yy_c_buf_p) = (GENLIB_yytext_ptr) + YY_MORE_ADJ;

					GENLIB_yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (GENLIB_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(GENLIB_yy_c_buf_p) =
					(GENLIB_yytext_ptr) + GENLIB_yy_amount_of_matched_text;

				GENLIB_yy_current_state = GENLIB_yy_get_previous_state(  );

				GENLIB_yy_cp = (GENLIB_yy_c_buf_p);
				GENLIB_yy_bp = (GENLIB_yytext_ptr) + YY_MORE_ADJ;
				goto GENLIB_yy_match;

			case EOB_ACT_LAST_MATCH:
				(GENLIB_yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf[(GENLIB_yy_n_chars)];

				GENLIB_yy_current_state = GENLIB_yy_get_previous_state(  );

				GENLIB_yy_cp = (GENLIB_yy_c_buf_p);
				GENLIB_yy_bp = (GENLIB_yytext_ptr) + YY_MORE_ADJ;
				goto GENLIB_yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of GENLIB_yylex */

/* GENLIB_yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int GENLIB_yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf;
	char *source = (GENLIB_yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (GENLIB_yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf[(GENLIB_yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (GENLIB_yy_c_buf_p) - (GENLIB_yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((GENLIB_yy_c_buf_p) - (GENLIB_yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_n_chars = (GENLIB_yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int GENLIB_yy_c_buf_p_offset =
				(int) ((GENLIB_yy_c_buf_p) - b->GENLIB_yy_ch_buf);

			if ( b->GENLIB_yy_is_our_buffer )
				{
				int new_size = b->GENLIB_yy_buf_size * 2;

				if ( new_size <= 0 )
					b->GENLIB_yy_buf_size += b->GENLIB_yy_buf_size / 8;
				else
					b->GENLIB_yy_buf_size *= 2;

				b->GENLIB_yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					GENLIB_yyrealloc( (void *) b->GENLIB_yy_ch_buf,
							 (GENLIB_yy_size_t) (b->GENLIB_yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->GENLIB_yy_ch_buf = NULL;

			if ( ! b->GENLIB_yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(GENLIB_yy_c_buf_p) = &b->GENLIB_yy_ch_buf[GENLIB_yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf[number_to_move]),
			(GENLIB_yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_n_chars = (GENLIB_yy_n_chars);
		}

	if ( (GENLIB_yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			GENLIB_yyrestart( GENLIB_yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((GENLIB_yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (GENLIB_yy_n_chars) + number_to_move + ((GENLIB_yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf = (char *) GENLIB_yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf, (GENLIB_yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in GENLIB_yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buf_size = (int) (new_size - 2);
	}

	(GENLIB_yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf[(GENLIB_yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf[(GENLIB_yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(GENLIB_yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf[0];

	return ret_val;
}

/* GENLIB_yy_get_previous_state - get the state just before the EOB char was reached */

    static GENLIB_yy_state_type GENLIB_yy_get_previous_state (void)
{
	GENLIB_yy_state_type GENLIB_yy_current_state;
	char *GENLIB_yy_cp;
    
	GENLIB_yy_current_state = (GENLIB_yy_start);

	for ( GENLIB_yy_cp = (GENLIB_yytext_ptr) + YY_MORE_ADJ; GENLIB_yy_cp < (GENLIB_yy_c_buf_p); ++GENLIB_yy_cp )
		{
		YY_CHAR GENLIB_yy_c = (*GENLIB_yy_cp ? GENLIB_yy_ec[YY_SC_TO_UI(*GENLIB_yy_cp)] : 1);
		if ( GENLIB_yy_accept[GENLIB_yy_current_state] )
			{
			(GENLIB_yy_last_accepting_state) = GENLIB_yy_current_state;
			(GENLIB_yy_last_accepting_cpos) = GENLIB_yy_cp;
			}
		while ( GENLIB_yy_chk[GENLIB_yy_base[GENLIB_yy_current_state] + GENLIB_yy_c] != GENLIB_yy_current_state )
			{
			GENLIB_yy_current_state = (int) GENLIB_yy_def[GENLIB_yy_current_state];
			if ( GENLIB_yy_current_state >= 73 )
				GENLIB_yy_c = GENLIB_yy_meta[GENLIB_yy_c];
			}
		GENLIB_yy_current_state = GENLIB_yy_nxt[GENLIB_yy_base[GENLIB_yy_current_state] + GENLIB_yy_c];
		}

	return GENLIB_yy_current_state;
}

/* GENLIB_yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = GENLIB_yy_try_NUL_trans( current_state );
 */
    static GENLIB_yy_state_type GENLIB_yy_try_NUL_trans  (GENLIB_yy_state_type GENLIB_yy_current_state )
{
	int GENLIB_yy_is_jam;
    	char *GENLIB_yy_cp = (GENLIB_yy_c_buf_p);

	YY_CHAR GENLIB_yy_c = 1;
	if ( GENLIB_yy_accept[GENLIB_yy_current_state] )
		{
		(GENLIB_yy_last_accepting_state) = GENLIB_yy_current_state;
		(GENLIB_yy_last_accepting_cpos) = GENLIB_yy_cp;
		}
	while ( GENLIB_yy_chk[GENLIB_yy_base[GENLIB_yy_current_state] + GENLIB_yy_c] != GENLIB_yy_current_state )
		{
		GENLIB_yy_current_state = (int) GENLIB_yy_def[GENLIB_yy_current_state];
		if ( GENLIB_yy_current_state >= 73 )
			GENLIB_yy_c = GENLIB_yy_meta[GENLIB_yy_c];
		}
	GENLIB_yy_current_state = GENLIB_yy_nxt[GENLIB_yy_base[GENLIB_yy_current_state] + GENLIB_yy_c];
	GENLIB_yy_is_jam = (GENLIB_yy_current_state == 72);

		return GENLIB_yy_is_jam ? 0 : GENLIB_yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void GENLIB_yyunput (int c, char * GENLIB_yy_bp )
{
	char *GENLIB_yy_cp;
    
    GENLIB_yy_cp = (GENLIB_yy_c_buf_p);

	/* undo effects of setting up GENLIB_yytext */
	*GENLIB_yy_cp = (GENLIB_yy_hold_char);

	if ( GENLIB_yy_cp < YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (GENLIB_yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf )
			*--dest = *--source;

		GENLIB_yy_cp += (int) (dest - source);
		GENLIB_yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_n_chars =
			(GENLIB_yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buf_size;

		if ( GENLIB_yy_cp < YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--GENLIB_yy_cp = (char) c;

	(GENLIB_yytext_ptr) = GENLIB_yy_bp;
	(GENLIB_yy_hold_char) = *GENLIB_yy_cp;
	(GENLIB_yy_c_buf_p) = GENLIB_yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int GENLIB_yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(GENLIB_yy_c_buf_p) = (GENLIB_yy_hold_char);

	if ( *(GENLIB_yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* GENLIB_yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (GENLIB_yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_ch_buf[(GENLIB_yy_n_chars)] )
			/* This was really a NUL. */
			*(GENLIB_yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((GENLIB_yy_c_buf_p) - (GENLIB_yytext_ptr));
			++(GENLIB_yy_c_buf_p);

			switch ( GENLIB_yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because GENLIB_yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					GENLIB_yyrestart( GENLIB_yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( GENLIB_yywrap(  ) )
						return 0;

					if ( ! (GENLIB_yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return GENLIB_yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(GENLIB_yy_c_buf_p) = (GENLIB_yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (GENLIB_yy_c_buf_p);	/* cast for 8-bit char's */
	*(GENLIB_yy_c_buf_p) = '\0';	/* preserve GENLIB_yytext */
	(GENLIB_yy_hold_char) = *++(GENLIB_yy_c_buf_p);

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void GENLIB_yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        GENLIB_yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            GENLIB_yy_create_buffer( GENLIB_yyin, YY_BUF_SIZE );
	}

	GENLIB_yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	GENLIB_yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void GENLIB_yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		GENLIB_yypop_buffer_state();
	 *		GENLIB_yypush_buffer_state(new_buffer);
     */
	GENLIB_yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(GENLIB_yy_c_buf_p) = (GENLIB_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buf_pos = (GENLIB_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_n_chars = (GENLIB_yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	GENLIB_yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (GENLIB_yywrap()) processing, but the only time this flag
	 * is looked at is after GENLIB_yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(GENLIB_yy_did_buffer_switch_on_eof) = 1;
}

static void GENLIB_yy_load_buffer_state  (void)
{
    	(GENLIB_yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_n_chars;
	(GENLIB_yytext_ptr) = (GENLIB_yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buf_pos;
	GENLIB_yyin = YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_input_file;
	(GENLIB_yy_hold_char) = *(GENLIB_yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE GENLIB_yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) GENLIB_yyalloc( sizeof( struct GENLIB_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in GENLIB_yy_create_buffer()" );

	b->GENLIB_yy_buf_size = size;

	/* GENLIB_yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->GENLIB_yy_ch_buf = (char *) GENLIB_yyalloc( (GENLIB_yy_size_t) (b->GENLIB_yy_buf_size + 2)  );
	if ( ! b->GENLIB_yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in GENLIB_yy_create_buffer()" );

	b->GENLIB_yy_is_our_buffer = 1;

	GENLIB_yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with GENLIB_yy_create_buffer()
 * 
 */
    void GENLIB_yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->GENLIB_yy_is_our_buffer )
		GENLIB_yyfree( (void *) b->GENLIB_yy_ch_buf  );

	GENLIB_yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a GENLIB_yyrestart() or at EOF.
 */
    static void GENLIB_yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	GENLIB_yy_flush_buffer( b );

	b->GENLIB_yy_input_file = file;
	b->GENLIB_yy_fill_buffer = 1;

    /* If b is the current buffer, then GENLIB_yy_init_buffer was _probably_
     * called from GENLIB_yyrestart() or through GENLIB_yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->GENLIB_yy_bs_lineno = 1;
        b->GENLIB_yy_bs_column = 0;
    }

        b->GENLIB_yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void GENLIB_yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->GENLIB_yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->GENLIB_yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->GENLIB_yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->GENLIB_yy_buf_pos = &b->GENLIB_yy_ch_buf[0];

	b->GENLIB_yy_at_bol = 1;
	b->GENLIB_yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		GENLIB_yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void GENLIB_yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	GENLIB_yyensure_buffer_stack();

	/* This block is copied from GENLIB_yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(GENLIB_yy_c_buf_p) = (GENLIB_yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_buf_pos = (GENLIB_yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->GENLIB_yy_n_chars = (GENLIB_yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(GENLIB_yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from GENLIB_yy_switch_to_buffer. */
	GENLIB_yy_load_buffer_state(  );
	(GENLIB_yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void GENLIB_yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	GENLIB_yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((GENLIB_yy_buffer_stack_top) > 0)
		--(GENLIB_yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		GENLIB_yy_load_buffer_state(  );
		(GENLIB_yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void GENLIB_yyensure_buffer_stack (void)
{
	GENLIB_yy_size_t num_to_alloc;
    
	if (!(GENLIB_yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(GENLIB_yy_buffer_stack) = (struct GENLIB_yy_buffer_state**)GENLIB_yyalloc
								(num_to_alloc * sizeof(struct GENLIB_yy_buffer_state*)
								);
		if ( ! (GENLIB_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in GENLIB_yyensure_buffer_stack()" );

		memset((GENLIB_yy_buffer_stack), 0, num_to_alloc * sizeof(struct GENLIB_yy_buffer_state*));

		(GENLIB_yy_buffer_stack_max) = num_to_alloc;
		(GENLIB_yy_buffer_stack_top) = 0;
		return;
	}

	if ((GENLIB_yy_buffer_stack_top) >= ((GENLIB_yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		GENLIB_yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (GENLIB_yy_buffer_stack_max) + grow_size;
		(GENLIB_yy_buffer_stack) = (struct GENLIB_yy_buffer_state**)GENLIB_yyrealloc
								((GENLIB_yy_buffer_stack),
								num_to_alloc * sizeof(struct GENLIB_yy_buffer_state*)
								);
		if ( ! (GENLIB_yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in GENLIB_yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((GENLIB_yy_buffer_stack) + (GENLIB_yy_buffer_stack_max), 0, grow_size * sizeof(struct GENLIB_yy_buffer_state*));
		(GENLIB_yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE GENLIB_yy_scan_buffer  (char * base, GENLIB_yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) GENLIB_yyalloc( sizeof( struct GENLIB_yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in GENLIB_yy_scan_buffer()" );

	b->GENLIB_yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->GENLIB_yy_buf_pos = b->GENLIB_yy_ch_buf = base;
	b->GENLIB_yy_is_our_buffer = 0;
	b->GENLIB_yy_input_file = NULL;
	b->GENLIB_yy_n_chars = b->GENLIB_yy_buf_size;
	b->GENLIB_yy_is_interactive = 0;
	b->GENLIB_yy_at_bol = 1;
	b->GENLIB_yy_fill_buffer = 0;
	b->GENLIB_yy_buffer_status = YY_BUFFER_NEW;

	GENLIB_yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to GENLIB_yylex() will
 * scan from a @e copy of @a str.
 * @param GENLIB_yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       GENLIB_yy_scan_bytes() instead.
 */
YY_BUFFER_STATE GENLIB_yy_scan_string (const char * GENLIB_yystr )
{
    
	return GENLIB_yy_scan_bytes( GENLIB_yystr, (int) strlen(GENLIB_yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to GENLIB_yylex() will
 * scan from a @e copy of @a bytes.
 * @param GENLIB_yybytes the byte buffer to scan
 * @param _GENLIB_yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE GENLIB_yy_scan_bytes  (const char * GENLIB_yybytes, int  _GENLIB_yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	GENLIB_yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (GENLIB_yy_size_t) (_GENLIB_yybytes_len + 2);
	buf = (char *) GENLIB_yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in GENLIB_yy_scan_bytes()" );

	for ( i = 0; i < _GENLIB_yybytes_len; ++i )
		buf[i] = GENLIB_yybytes[i];

	buf[_GENLIB_yybytes_len] = buf[_GENLIB_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = GENLIB_yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in GENLIB_yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->GENLIB_yy_is_our_buffer = 1;

	return b;
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void GENLIB_yynoreturn GENLIB_yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine GENLIB_yyless() so it works in section 3 code. */

#undef GENLIB_yyless
#define GENLIB_yyless(n) \
	do \
		{ \
		/* Undo effects of setting up GENLIB_yytext. */ \
        int GENLIB_yyless_macro_arg = (n); \
        YY_LESS_LINENO(GENLIB_yyless_macro_arg);\
		GENLIB_yytext[GENLIB_yyleng] = (GENLIB_yy_hold_char); \
		(GENLIB_yy_c_buf_p) = GENLIB_yytext + GENLIB_yyless_macro_arg; \
		(GENLIB_yy_hold_char) = *(GENLIB_yy_c_buf_p); \
		*(GENLIB_yy_c_buf_p) = '\0'; \
		GENLIB_yyleng = GENLIB_yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int GENLIB_yyget_lineno  (void)
{
    
    return GENLIB_yylineno;
}

/** Get the input stream.
 * 
 */
FILE *GENLIB_yyget_in  (void)
{
        return GENLIB_yyin;
}

/** Get the output stream.
 * 
 */
FILE *GENLIB_yyget_out  (void)
{
        return GENLIB_yyout;
}

/** Get the length of the current token.
 * 
 */
int GENLIB_yyget_leng  (void)
{
        return GENLIB_yyleng;
}

/** Get the current token.
 * 
 */

char *GENLIB_yyget_text  (void)
{
        return GENLIB_yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void GENLIB_yyset_lineno (int  _line_number )
{
    
    GENLIB_yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see GENLIB_yy_switch_to_buffer
 */
void GENLIB_yyset_in (FILE *  _in_str )
{
        GENLIB_yyin = _in_str ;
}

void GENLIB_yyset_out (FILE *  _out_str )
{
        GENLIB_yyout = _out_str ;
}

int GENLIB_yyget_debug  (void)
{
        return GENLIB_yy_flex_debug;
}

void GENLIB_yyset_debug (int  _bdebug )
{
        GENLIB_yy_flex_debug = _bdebug ;
}

static int GENLIB_yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from GENLIB_yylex_destroy(), so don't allocate here.
     */

    (GENLIB_yy_buffer_stack) = NULL;
    (GENLIB_yy_buffer_stack_top) = 0;
    (GENLIB_yy_buffer_stack_max) = 0;
    (GENLIB_yy_c_buf_p) = NULL;
    (GENLIB_yy_init) = 0;
    (GENLIB_yy_start) = 0;

/* Defined in main.c */
#ifdef YY_STDINIT
    GENLIB_yyin = stdin;
    GENLIB_yyout = stdout;
#else
    GENLIB_yyin = NULL;
    GENLIB_yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * GENLIB_yylex_init()
     */
    return 0;
}

/* GENLIB_yylex_destroy is for both reentrant and non-reentrant scanners. */
int GENLIB_yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		GENLIB_yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		GENLIB_yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	GENLIB_yyfree((GENLIB_yy_buffer_stack) );
	(GENLIB_yy_buffer_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * GENLIB_yylex() is called, initialization will occur. */
    GENLIB_yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef GENLIB_yytext_ptr
static void GENLIB_yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int GENLIB_yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *GENLIB_yyalloc (GENLIB_yy_size_t  size )
{
			return malloc(size);
}

void *GENLIB_yyrealloc  (void * ptr, GENLIB_yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void GENLIB_yyfree (void * ptr )
{
			free( (char *) ptr );	/* see GENLIB_yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "GENLIB_yytables"

#line 62 "readliblex.l"


#if 0 /* #ifndef FLEX_SCANNER */
static int
input()
{
    register int c;

    if (nbuffer > 0) {
	c = buffer[--nbuffer];
    } else {
	if (file_mode) {
	    c = getc(GENLIB_yyin);
	} else {
	    c = *file_string;
	    if (c != 0) file_string++;
	}
    }
    if (c == '\n') read_lineno++;
    if (c == EOF) c = 0;
    return c;
}


static int
unput(c)
int c;
{
    if (nbuffer < 20) buffer[nbuffer++] = c;
    if (c == '\n') read_lineno--;
    return c;
}
#else

char *genlib_inp_ptr;
char *genlib_inp_lim;

int genlib_input(char* buf, int max_size)
{
    char c;
    int i, n;

    if (! file_mode) {
	if (max_size > (genlib_inp_lim - genlib_inp_ptr))
	    n = genlib_inp_lim - genlib_inp_ptr;
	else 
	    n = max_size;	
	if (n > 0) {
	    for (i = 0; i < n; i++)
		if (buf[i] == '\n') {
		    read_lineno++;
		    i++;
		    break;
		}
	    memcpy (buf, genlib_inp_ptr, i);
	    genlib_inp_ptr += i;
	}
    } else {
	c = getc(GENLIB_yyin);
	if (c == '\n') read_lineno++;
	buf[0] = (c == EOF) ? (n = 0, YY_NULL) : (n = 1, c);
    }
    return n;
}
#endif

int
library_setup_file(fp, filename)
FILE *fp;
char *filename;
{
    GENLIB_yyin = fp;
#if 1 /* #ifdef FLEX_SCANNER */
    GENLIB_yy_switch_to_buffer( GENLIB_yy_create_buffer( GENLIB_yyin, YY_BUF_SIZE ) );
    GENLIB_yyrestart(GENLIB_yyin); 
    BEGIN(INITIAL);
#endif
    file_mode = 1;
    nbuffer = 0;
    read_register_filename(filename);
}

int
library_setup_string(string)
char *string;
{
    file_string = string;
    file_mode = 0;
#if 1 /* #ifdef FLEX_SCANNER */
    GENLIB_yy_switch_to_buffer(
                 GENLIB_yy_create_buffer( GENLIB_yyin, YY_BUF_SIZE ) );
    GENLIB_yyrestart(GENLIB_yyin); 
    genlib_inp_lim = string + strlen(string);
    genlib_inp_ptr = string;
#endif
    nbuffer = 0;
    read_register_filename(NIL(char));
}

#undef GENLIB_yywrap 
int
GENLIB_yywrap()
{
    return 1;
}

